const fs = require("fs");
const path = require("path");

const CSS_DIR = path.join(__dirname, "css");
const OUT = path.join(__dirname, "style.css");

const PARTS = [
  "tokens.css",
  "typography.css",
  "nav.css",
  "buttons.css",
  "hero.css",
  "landing.css",
  "dashboard.css",
  "pages.css",
  "access.css",
  "components.css",
  "footer.css",
];

const header = `/* Auto-generated by build-css — do not edit directly. */\n`;

const body = PARTS.map((file) => {
  const p = path.join(CSS_DIR, file);
  if (!fs.existsSync(p)) {
    console.warn(`  warn: ${file} not found, skipping`);
    return "";
  }
  return `/* ── ${file} ── */\n${fs.readFileSync(p, "utf8")}`;
}).join("\n\n");

fs.writeFileSync(OUT, header + body + "\n");
console.log(`style.css built (${PARTS.length} partials)`);
