/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        canvas: "var(--canvas)",
        "surface-soft": "var(--surface-soft)",
        "surface-card": "var(--surface-card)",
        "surface-cream-strong": "var(--surface-cream-strong)",
        "surface-dark": "var(--surface-dark)",
        "surface-dark-elevated": "var(--surface-dark-elevated)",
        "surface-dark-soft": "var(--surface-dark-soft)",
        ink: "var(--ink)",
        "body-c": "var(--body-c)",
        "body-strong": "var(--body-strong)",
        muted: "var(--muted)",
        "muted-soft": "var(--muted-soft)",
        hairline: "var(--hairline)",
        "hairline-soft": "var(--hairline-soft)",
        primary: {
          DEFAULT: "var(--primary)",
          active: "var(--primary-active)",
          disabled: "var(--primary-disabled)",
          foreground: "var(--on-primary)",
        },
        "on-primary": "var(--on-primary)",
        "on-dark": "var(--on-dark)",
        "on-dark-soft": "var(--on-dark-soft)",
        "accent-teal": "var(--accent-teal)",
        "accent-amber": "var(--accent-amber)",
        success: "var(--success)",
        warning: "var(--warning)",
        error: "var(--error)",
        "scene-bg": "var(--scene-bg)",
        "hub-glow": "var(--hub-glow)",
        "hub-active": "var(--hub-active)",
        "app-inactive": "var(--app-inactive)",
        "app-active": "var(--app-active)",
        "access-card": "var(--access-card)",
        "employee-color": "var(--employee-color)",
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        pill: "var(--radius-pill)",
      },
      fontFamily: {
        display: ["Copernicus", "Tiempos Headline", "'EB Garamond'", "Garamond", "serif"],
        body: ["Inter", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        mono: ["'JetBrains Mono'", "ui-monospace", "monospace"],
      },
      fontSize: {
        'display-xl': ['64px', { lineHeight: '1.05', letterSpacing: '-0.023em', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.021em', fontWeight: '400' }],
        'display-md': ['36px', { lineHeight: '1.15', letterSpacing: '-0.014em', fontWeight: '400' }],
        'display-sm': ['28px', { lineHeight: '1.2', letterSpacing: '-0.011em', fontWeight: '400' }],
        'title-lg': ['22px', { lineHeight: '1.3', letterSpacing: '0', fontWeight: '500' }],
        'title-md': ['18px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '500' }],
        'title-sm': ['16px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.55', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.55', letterSpacing: '0', fontWeight: '400' }],
        caption: ['13px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '500' }],
        'caption-upper': ['12px', { lineHeight: '1.4', letterSpacing: '0.094em', fontWeight: '500' }],
      },
      spacing: {
        section: '96px',
      },
    },
  },
  plugins: [],
}
